<<<<<<< HEAD
# Generated by Django 4.2 on 2023-04-14 20:07
=======
# Generated by Django 4.2 on 2023-04-14 18:05
>>>>>>> 84eabc0d4274f3307f1b223087b2c18099563281

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('latin_name', models.CharField(max_length=50)),
                ('img', models.URLField()),
                ('window_pref', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
<<<<<<< HEAD
                ('windows', models.CharField(default='Enter Cardinal Direction', max_length=50)),
=======
>>>>>>> 84eabc0d4274f3307f1b223087b2c18099563281
                ('user', models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
