# Generated by Django 4.2 on 2023-04-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newgrowth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='windows',
            field=models.CharField(default='Enter Cardinal Direction', max_length=50),
        ),
    ]
