# Generated by Django 4.2 on 2023-04-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newgrowth_app', '0002_user_profile_windows'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='drought_tol',
            field=models.BooleanField(default=False, verbose_name='Drought Tolerant'),
        ),
        migrations.AddField(
            model_name='plant',
            name='toxic',
            field=models.BooleanField(default=False, verbose_name='Toxic'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='pets',
            field=models.BooleanField(default=False, verbose_name='Has Pets'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='travel_freq',
            field=models.BooleanField(default=False, verbose_name='Travels Frequently'),
        ),
    ]
